TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

TWELVEDATA_API_KEY = "YOUR_TWELVEDATA_KEY"

PAIRS = {
    "EUR/USD": "EUR/USD",
    "GBP/USD": "GBP/USD",
    "USD/JPY": "USD/JPY",
    "XAU/USD": "XAU/USD"
}
